version: '3.8'

services:
  kali:
    build:
      context: .
      dockerfile: ./docker/kali/Dockerfile.${KALI_TOOLKIT:-headless}
    volumes:
      - ./pentes:/pentest
    networks:
      - kali-network

networks:
  kali-network:
    driver: bridge